### PR TITLE
[Chat] Refactor chat initialization/user handling logic

### LINKED ISSUE #224: Refactor Stream Chat client integration
The initialization logic for integrating with Stream Chat SDK is messy and doesn't always properly work.
It's stubbornly caching old user tokens, and generally flimsy.

There's redundancy between **LiveStream** and **Group** chat usages, too.

### LINKED ISSUE #227: [LiveStream] Video theater mode value doesn't restore when false
There's a sneaky falsy logic crack when restoring a `localStorage` value for `CF:theater-mode` when it is `false`.
Since it's falsy, it returns the `initialValue` / default fallback, which is `true`.

This means if you turn off theater mode, even though the value is properly stored in `localStorage`, when it is restored on refresh, it gets reset to `true`.

### LINKED ISSUE #228: Authenticated data in Apollo client cache not cleared on logout
CleanShot 2020-12-18 at 17 27 25@2x

### LINKED ISSUE #229: Incorrect Breakpoint on Group Single
Group Resources looking a little funky with the current breakpoints

image

### PR DESCRIPTION
**Pull request by rkdavidson**
# Related Issue
- Fixes #224 
- Fixes #227 
- Fixes #228 
- Fixes #229

# Changes or Updates
- Lifts the critical Stream Chat SDK integration to a new `useChat` hook
- Substantially simplifies the `useEffect` that reacts to user auth state changes
- Updates `stream-chat` dependency package versions
- Fixes #227 , discovered during dev for #224 
- Fixes #228 , which was a red herring problem affecting the `useChat` logic (switching users would momentarily use previous users' Apollo cache data)
- Cleans up a few prop type / eslint warnings along the way

# Test Instructions

**Local API changes**
In order to fully test auth flows for LiveStream chat, you need some local API changes. These changes bypass the filters etc that hide test events from public users. This lets you view the 24/7 test livestream locally, even when logged out.

You can either manually apply the changes in [this gist](https://gist.github.com/rkdavidson/75ce0be952ddfa87ee1f29ed79f15bd1), or follow a few steps to apply them automatically:
1. Download [the gist](https://gist.github.com/rkdavidson/75ce0be952ddfa87ee1f29ed79f15bd1) file to your `apollos-api` repo
1. Run `git apply pr230.patch`
1. Continue testing instructions...
1. When finished, run `git apply pr230.patch --reverse && rm pr230.patch` to undo the changes

### LiveStream Chat
1. Make sure you have sandbox mode enabled for the **web-app**
1. Go to http://local.christfellowship.church:3000/events/test-event-24-hour-live-stream
1. 🔸 Verify that chat initializes properly as you log in and out, change users, refresh the page while logged out, refresh while logged in, etc

### Group Chat: in Sandbox mode
1. Go to a local group from http://local.christfellowship.church:3000/groups
2. 🔸 Verify the group's chat still connects as expected

### Group Chat: non-Sandbox mode
1. Disable sandbox mode and restart web server
2. Go to a local group from http://local.christfellowship.church:3000/groups
3. 🔸 Verify the group's chat still connects as expected
4. 🔸 Verify the group's resources aren't full page width on desktop

# Screenshots
|Caption|Screenshot/Gif|
|---|---|
|`useChat` hook on LiveStream chat||
|`useChat` hook on Group chat||
|Fix for #227, properly remember `TheaterMode` state on refresh||
|Fix for #229||

# Tests
- [ ] needed snapshots updated
- [ ] mobile tested
- [ ] latest update from master

### CODE REVIEW

File: src/content-single/EventContentItem/components/CallsToAction.js [hunk 1]
```diff
@@ -52,12 +52,23 @@ const CallsToAction = ({ nodeId, eventTitle, items, hasEvents, eventStartTime })
...
+        () => setCTA(filterItems(items, eventStartTime)),
+        MINUTE
+      );
+
+      return () => {
+        clearInterval(intervalId);
+      };
+    }
+  }, []);
+
```
Comment (rkdavidson) [inline src/content-single/EventContentItem/components/CallsToAction.js:67]: Fixes memory leak warning on unmounted component

File: src/content-single/EventContentItem/components/EventPanel.js [hunk 2]
```diff
@@ -44,6 +44,7 @@ const PanelBody = styled.div`
   z-index: 0;
   width: 100%;
   height: 100%;
+  background: ${({ theme }) => theme.card.background};
```
Comment (rkdavidson) [inline src/content-single/EventContentItem/components/EventPanel.js:47]: Fixes bug with loading state for Chat, where background was transparent

File: src/content-single/EventContentItem/components/EventChat.js [hunk 3]
```diff
@@ -108,132 +111,89 @@ const EventChat = ({ event, channelId, channelType, onWatcherCountChange }) => {
...
-      // All DM channels, whether recent or not
-      const dmChannelsResponse = await ChatUtils.getUserDmChannels();
-      setDmChannels(dmChannelsResponse);
-
-      // Only recently active DM channels
-      const recentDmChannels = ChatUtils.filterRecentDmChannels(dmChannelsResponse);
-      setDmChannelsVisible(recentDmChannels);
-      console.groupEnd();
-    };
+  // ✂️ ----------------------------------------------------------------------------------------------
```
Comment (rkdavidson) [inline src/content-single/EventContentItem/components/EventChat.js:122]: These `// ✂️ -----` code comment markers delineate my next target for a `hook` refactor.
Can lift some of this DMs channel fetching/event handling logic up and out of `render()`.

File: src/stream-chat-client/chatRoles.js [hunk 4]
```diff
@@ -3,6 +3,7 @@ const ChatRoles = Object.freeze({
   MEMBER: 'USER', // Treat 'user' and 'member' as the same thing
   MODERATOR: 'MODERATOR',
   GUEST: 'GUEST',
+  ANONYMOUS: 'ANONYMOUS',
```
Comment (rkdavidson) [inline src/stream-chat-client/chatRoles.js:6]: Switching unauthenticated users from `GUEST` to `ANONYMOUS` in the new `useChat` hook, so this role added here and other places where `GUEST` was previously used.

The **anonymous** user type is more reflective of our needs for livestream, and doesn't count towards Monthly Active Users.
The **guest** user _does_ count towards Monthly Active Users, and I think I had confused these terms at some point because I thought these were backwards 🤔.

Stream docs reference:
- 🔗 [Anonymous Users](https://getstream.io/chat/docs/anon/?language=js)
- 🔗 [Guest Users](https://getstream.io/chat/docs/guest_users/?language=js)

**Review by drewbarontini — COMMENTED** [review]
I just wanted to note that I've reviewed the code changes and they're looking good! 👍

I'll have to pull down the changes and get the local API changes running to test fully 🙌

**Comment by asleepingpanda** [comment]
@rkdavidson is this ready to go live? I would love to push it as our online team is starting to test this. You feel good about this, still?

**Review by asleepingpanda — APPROVED** [review]
Looks good to me! I'm good to get this thing out and tested by our team.

**Comment by rkdavidson** [comment]
Hey @asleepingpanda had to update `master`, so feel free to re-approve and merge whenever you're ready.
I have no further changes and I think timing is good whenever to merge 👍.
